# Generated by Django 5.0.6 on 2024-06-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('users', '0009_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homework',
            new_name='Lesson',
        ),
    ]
