# Generated by Django 5.0.6 on 2024-06-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_homework_lesson'),
        ('users', '0009_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('team', 'title')},
        ),
    ]
