# Generated by Django 5.0.6 on 2024-06-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_lesson_title_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='homework_status',
            field=models.BooleanField(default=False),
        ),
    ]
